@startuml
'https://plantuml.com/class-diagram

abstract class NameSorter
abstract class NameSorting

NameSorting <|-- NameSorter
NameSorter <|-- NameSorting



class NameSorter {
InputData
OutputData
}

class NameSorting {
Map<Integer, String> SortData
}


@enduml