@startuml
'https://plantuml.com/class-diagram

abstract class App
abstract class WebsiteGenerator

WebsiteGenerator <|-- App


class App {
Input
}

class WebsiteGenerator{
createFolders
createIndex
}



@enduml